set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports MDIO_PHY_0_mdio_io]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports MDIO_PHY_0_mdc]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {MII_0_rd[3]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {MII_0_rd[2]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {MII_0_rd[1]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {MII_0_rd[0]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {MII_0_td[3]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {MII_0_td[2]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {MII_0_td[1]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {MII_0_td[0]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports MII_0_rx_dv]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports MII_0_rxclk]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {MII_0_tx_en[0]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports MII_0_txclk]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports SYSCLK25]

set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {GPIO_0_0_tri_io[0]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {GPIO_0_0_tri_io[1]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {GPIO_0_0_tri_io[2]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {GPIO_0_0_tri_io[3]}]

set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {BCLK_O_1[0]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {LRCLK_O_1[0]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {SDATA[0]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {SDATA[1]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {SDATA[2]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {SDATA[3]}]

set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports SPI0_SS_O_0]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports SPI0_MOSI_O_0]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports SPI0_MISO_I_0]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports SPI0_SCLK_O_0]

set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports AUDIOCLK]
